---
- name: "Tuning: Load kernel modules"
  community.general.modprobe:
    name: overlay
    state: present
  failed_when: false  # Besser als ignore_errors f√ºr den Linter

- name: "Tuning: Apply sysctl parameters"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true      # "true" statt "yes"
  failed_when: false
