galaxy_info:
  author: "Nova User"
  description: System Tuning Role
  company: "Nova Corp"
  license: MIT
  min_ansible_version: "2.1"  # Muss ein String sein (in Anf√ºhrungszeichen)
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags: []
dependencies: []
