galaxy_info:
  author: your name
  description: your role description
  company: your company (optional)

  # If the issue persists on the platform, uncomment the
  # following line and set it to the platform name.
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all

  galaxy_tags: []

dependencies: []