version: '3.8'
services:
  ansible-controller:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/project
      - /tmp/ssh-PsoPKt9lfcxY/agent.156426:/run/host-ssh-agent/storage
    environment:
      - SSH_AUTH_SOCK=/run/host-ssh-agent/storage
    networks:
      - ansible-network

networks:
  ansible-network:
    name: ansible-network
